### PR TITLE
schema created

### PR DESCRIPTION
**Pull request by tinglu12**

### CODE REVIEW

**Review by amoghmadireddi — APPROVED** [review]
Looks good!

**Review by jennweir — CHANGES_REQUESTED** [review]
This looks like a good start. I think there might be some action items to fix before merging with main. 
1. Is there a reason why owner is in quotes in the post table?
    If there is a specific reason for this, please follow up with an explanation. I'm not familiar with this syntax but it might be intended for what you want!
2. The type BYTEA for the profile picture is not necessary. To store images we will use an Amazon S3 bucket, which only requires a string that specifies an image name. We can use something like this instead:
profile_picture VARCHAR(256) NOT NULL,
3. I'm not sure line 20 is supposed to be for but if its a work in progress that is fine. We will wait to merge with main until it is either finished or removed.

**Comment by jennweir** [comment]
> This looks like a good start. I think there might be some action items to fix before merging with main.
> 
> 1. Is there a reason why owner is in quotes in the post table?
>    If there is a specific reason for this, please follow up with an explanation. I'm not familiar with this syntax but it might be intended for what you want!
> 2. The type BYTEA for the profile picture is not necessary. To store images we will use an Amazon S3 bucket, which only requires a string that specifies an image name. We can use something like this instead:
>    profile_picture VARCHAR(256) NOT NULL,
> 3. I'm not sure line 20 is supposed to be for but if its a work in progress that is fine. We will wait to merge with main until it is either finished or removed.

I believe these have all been addressed. @tinglu12 I believe this branch is still in progress so we will wait to merge the PR for now until there are no errors in the application.

**Comment by jennweir** [comment]
Closing this PR because the schema created here was copied and pasted into the schema.sql file in the aws-connection branch. Since aws-connection has some other important fixes, that branch will be merged instead.

**Pull request closed without merging**
